name: Cypress Tests

on:
  pull_request:
    branches: master
  schedule:
    - cron: '0 3 * * 5' # Executa à meia-noite de sexta-feira
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.7
      
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.15.1'

    - name: Install Dependencies
      run: yarn install

    - name: Decode and import GPG key
      env:
        GPG_PRIVATE_KEY_BASE64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
      run: |
        echo "$GPG_PRIVATE_KEY_BASE64" | base64 --decode > private.key
        gpg --import private.key

    - name: Decrypt configuration file
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$GPG_PASSPHRASE" \
            --output cypress.config.js cypress.config.js.gpg

    - name: Clean up
      run: rm private.key

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        headless: true
