name: Cypress Tests

on:
  pull_request:
    branches: master
  schedule:
    - cron: '0 0 * * 4,5' # Executa à meia-noite de quinta e sexta-feira
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.7
      
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.15.1'

    - name: Install Dependencies
      run: yarn install

    - name: Decrypt Cypress Config
      run: gpg --quiet --batch --yes --decrypt --passphrase="$CYPRESS_CONFIG_PASSWORD" --output cypress.config.js cypress.config.js.gpg
      env:
        CYPRESS_CONFIG_PASSWORD: ${{ secrets.CYPRESS_CONFIG_PASSWORD }}

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        headless: true
