name: Cypress Tests

on:
  pull_request:
    branches: master
  schedule:
    - cron: '0 3 * * 5' # Executa à meia-noite de sexta-feira
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.7
      
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.15.1'

    - name: Install Dependencies
      run: yarn install

    - name: Check GPG version
      run: gpg --version
      shell: pwsh

    - name: Check PATH
      run: $env:PATH
      shell: pwsh

    - name: Decode and import GPG key
      env:
        GPG_PRIVATE_KEY_BASE64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
      shell: pwsh
      run: |
        $env:GPG_PRIVATE_KEY_BASE64 | Out-File -Encoding ASCII private_key_base64.txt
        certutil -decode private_key_base64.txt private.key
        gpg --batch --yes --import private.key

    - name: Create passphrase file
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      shell: pwsh
      run: |
        $env:GPG_PASSPHRASE | Out-File -NoNewline -Encoding ASCII temp_passphrase.txt

    - name: Decrypt configuration file
      shell: pwsh
      run: |
        Write-Host "Starting decryption..."
        gpg --decrypt --output cypress.config.js --batch --yes --passphrase-file temp_passphrase.txt cypress.config.js.gpg
        Write-Host "Decryption completed"
        if (Test-Path cypress.config.js) {
            Write-Host "cypress.config.js file created successfully"
        } else {
            Write-Host "Failed to create cypress.config.js file"
        }
      
    - name: Remove passphrase file
      if: always()
      shell: pwsh
      run: Remove-Item -Force -ErrorAction Ignore temp_passphrase.txt

    - name: Clean up
      run: |
        Remove-Item private_key_base64.txt
        Remove-Item private.key

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        headless: true
