name: Cypress Tests

on:
  pull_request:
    branches: master
  schedule:
    - cron: '0 3 * * 5' # Executa à meia-noite de sexta-feira
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.7
      
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.15.1'

    - name: Install Dependencies
      run: yarn install
    
    - name: Install GPG
      run: |
        choco install gnupg
        refreshenv
      shell: pwsh

    - name: Import PGP key
      env:
        PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
      shell: pwsh
      run: |
        $env:PGP_PRIVATE_KEY | Out-File -Encoding ASCII private.key
        gpg --batch --yes --import private.key
    
    - name: Decrypt configuration file
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      shell: pwsh
      run: |
        Write-Host "Starting decryption..."
        $passphrase = $env:PGP_PASSPHRASE
        $process = Start-Process -FilePath "gpg" -ArgumentList "--batch", "--yes", "--passphrase-fd", "0", "--decrypt", "--output", "cypress.config.js", "cypress.config.js.gpg" -NoNewWindow -PassThru -RedirectStandardInput ([System.IO.Path]::GetTempFileName())
        $process.StandardInput.WriteLine($passphrase)
        $process.StandardInput.Close()
        $process.WaitForExit()
        Write-Host "Decryption completed"
        if (Test-Path cypress.config.js) {
            Write-Host "cypress.config.js file created successfully"
        } else {
            Write-Host "Failed to create cypress.config.js file"
            exit 1
        }
    
    - name: Clean up
      if: always()
      shell: pwsh
      run: |
        Remove-Item -Force -ErrorAction Ignore private.key
    
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        headless: true
