name: Cypress Tests

on:
  pull_request:
    branches: master
  schedule:
    - cron: '0 3 * * 5' # Executa à meia-noite de sexta-feira
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.7
      
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.15.1'

    - name: Install Dependencies
      run: yarn install
    
    - name: Install GPG
      run: |
        sudo apt-get update
        sudo apt-get install -y gpg

    - name: Configure GPG
      run: |
        echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
        echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
        gpgconf --kill gpg-agent

    - name: Import PGP key
      env:
        PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
      run: |
        echo "$PGP_PRIVATE_KEY" > private.key
        gpg --batch --yes --import private.key
        # Definir confiança última na chave importada
        echo -e "5\ny\n" | gpg --command-fd 0 --expert --edit-key "karla.oliveira@twygo.com" trust
    
    - name: Debug GPG keys
      run: |
        gpg --list-secret-keys --keyid-format LONG
        gpg --list-keys --keyid-format LONG
    
    - name: Decrypt configuration file
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      run: |
        echo "Starting decryption..."
        # Criar diretório temporário para arquivo de senha
        mkdir -p /tmp/gpg
        echo "$PGP_PASSPHRASE" > /tmp/gpg/passphrase
        
        # Tentar decriptação com arquivo de senha
        gpg --batch --yes \
            --pinentry-mode loopback \
            --passphrase-file /tmp/gpg/passphrase \
            --decrypt \
            --output cypress.config.js \
            cypress.config.js.gpg
            
        # Limpar arquivo de senha
        rm -rf /tmp/gpg
        
        echo "Decryption completed"
        if [ -f cypress.config.js ]; then
          echo "cypress.config.js file created successfully"
          ls -la cypress.config.js
        else
          echo "Failed to create cypress.config.js file"
          exit 1
        fi
    
    - name: Clean up
      if: always()
      run: |
        rm -f private.key
        rm -rf ~/.gnupg
    
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        headless: true
