name: Cypress Tests

on:
  pull_request:
    branches: master
  schedule:
    - cron: '0 3 * * 5' # Executa à meia-noite de sexta-feira
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.7
      
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.15.1'

    - name: Install Dependencies
      run: yarn install
    
    - name: Install GPG
      run: |
        sudo apt-get update
        sudo apt-get install -y gpg

    - name: Import GPG key
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        echo "$GPG_PRIVATE_KEY" > private.key
        gpg --batch --yes --import private.key
    
    - name: Debug GPG keys
      run: gpg --list-secret-keys --keyid-format LONG
    
    - name: Decrypt configuration file
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo "Starting decryption..."
        echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --decrypt --output cypress.config.js cypress.config.js.gpg
        echo "Decryption completed"
        if [ -f cypress.config.js ]; then
          echo "cypress.config.js file created successfully"
          ls -la cypress.config.js
        else
          echo "Failed to create cypress.config.js file"
          exit 1
        fi
    
    - name: Clean up
      if: always()
      run: rm -f private.key
    
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        headless: true
